export const imageData = [
  {
    "id": 1,
    "src": "./src/assets/images/img1",
    "alt": "Design1",
    "designName": "3D Design and Animation Website",
    "designerName": "Zuco",
    "tags": ["yellow", "flower", "seed", "bright"],
    "categories": ["animation", "branding"],
    "likes": 5,
    "views": 100
  },
  {
    "id": 2,
    "src": "./src/assets/images/img2",
    "alt": "Design2",
    "designName": "Consumer Products",
    "designerName": "Aqua",
    "tags": ["blue", "ocean", "wave", "cool"],
    "categories": ["branding", "web design"],
    "likes": 12,
    "views": 230
  },
  {
    "id": 3,
    "src": "./src/assets/images/img3",
    "alt": "Design3",
    "designName": "Supermarket Store Interior",
    "designerName": "Rocky",
    "tags": ["mountain", "snow", "peak", "majestic"],
    "categories": ["typography", "branding"],
    "likes": 9,
    "views": 180
  },
  {
    "id": 4,
    "src": "./src/assets/images/img4",
    "alt": "Design4",
    "designName": "urban Ladder Furniture",
    "designerName": "Henry",
    "tags": ["city", "night", "lights", "bright"],
    "categories": ["web design", "illustration"],
    "likes": 20,
    "views": 300
  },
  {
    "id": 5,
    "src": "./src/assets/images/img5",
    "alt": "Design5",
    "designName": "Foreign Trade Men's Three Website",
    "designerName": "Sandy",
    "tags": ["desert", "sunset", "mirage", "warm"],
    "categories": ["typography", "branding"],
    "likes": 15,
    "views": 250
  },
  {
    "id": 6,
    "src": "./src/assets/images/img6",
    "alt": "Design6",
    "designName": "E-commerce Product",
    "designerName": "james",
    "tags": ["forest", "trees", "whisper", "calm"],
    "categories": ["illustration", "branding"],
    "likes": 11,
    "views": 190
  },
  {
    "id": 7,
    "src": "./src/assets/images/img7",
    "alt": "Design7",
    "designName": "Call Center Services",
    "designerName": "Star",
    "tags": ["galaxy", "stars", "space", "infinite"],
    "categories": ["animation", "web design"],
    "likes": 18,
    "views": 275
  },
  {
    "id": 8,
    "src": "./src/assets/images/img8",
    "alt": "Design8",
    "designName": "Healthcare Wordpress Webiste ",
    "designerName": "william",
    "tags": ["autumn", "leaves", "fall", "orange"],
    "categories": ["typography", "illustration"],
    "likes": 13,
    "views": 220
  },
  {
    "id": 9,
    "src": "./src/assets/images/img9",
    "alt": "Design9",
    "designName": "medisite website design",
    "designerName": "Snowy",
    "tags": ["winter", "snow", "wonderland", "white"],
    "categories": ["illustration", "branding"],
    "likes": 22,
    "views": 320
  },
  {
    "id": 10,
    "src": "./src/assets/images/img10",
    "alt": "Design10",
    "designName": "Grace super market",
    "designerName": "Dawn",
    "tags": ["sunrise", "bliss", "morning", "peaceful"],
    "categories": ["typography", "branding"],
    "likes": 17,
    "views": 260
  },
  {
    "id": 11,
    "src": "./src/assets/images/img11",
    "alt": "Design11",
    "designName": "Cryptocurrency wallet website",
    "designerName": "Stormy",
    "tags": ["rain", "days", "grey", "calm"],
    "categories": ["illustration", "web design"],
    "likes": 10,
    "views": 200
  },
  {
    "id": 12,
    "src": "./src/assets/images/img12",
    "alt": "Design12",
    "designName": "Lenin shirts ",
    "designerName": "Flora",
    "tags": ["spring", "bloom", "flowers", "colorful"],
    "categories": ["typography", "branding"],
    "likes": 14,
    "views": 240
  },
  {
    "id": 13,
    "src": "./src/assets/images/img13",
    "alt": "Design13",
    "designName": "Medicare Website",
    "designerName": "Sunny",
    "tags": ["summer", "vibes", "beach", "bright"],
    "categories": ["web design", "branding"],
    "likes": 16,
    "views": 280
  },
  {
    "id": 14,
    "src": "./src/assets/images/img14",
    "alt": "Design14",
    "designName": "Zacson website Redesign",
    "designerName": "City",
    "tags": ["urban", "jungle", "city", "green"],
    "categories": ["illustration", "web design"],
    "likes": 19,
    "views": 290
  },
  {
    "id": 15,
    "src": "./src/assets/images/img15",
    "alt": "Design15",
    "designName": "Work Studio wix website",
    "designerName": "Rural",
    "tags": ["country", "roads", "fields", "peaceful"],
    "categories": ["typography", "branding"],
    "likes": 8,
    "views": 170
  },
  {
    "id": 16,
    "src": "./src/assets/images/img16",
    "alt": "Design16",
    "designName": "Horse care & Training Center",
    "designerName": "Mystic",
    "tags": ["mountains", "mist", "mystic", "cool"],
    "categories": ["illustration", "branding"],
    "likes": 21,
    "views": 310
  },
  {
    "id": 17,
    "src": "./src/assets/images/img17",
    "alt": "Design17",
    "designName": "Interior design wordpress website",
    "designerName": "Dreamer",
    "tags": ["twilight", "dreams", "purple", "calm"],
    "categories": ["animation", "web design"],
    "likes": 23,
    "views": 330
  },
  {
    "id": 18,
    "src": "./src/assets/images/img18",
    "alt": "Design18",
    "designName": "Awesome wordpress website",
    "designerName": "Cosmo",
    "tags": ["cosmic", "space", "journey", "stars"],
    "categories": ["animation", "illustration"],
    "likes": 25,
    "views": 350
  },
  {
    "id": 19,
    "src": "./src/assets/images/img19",
    "alt": "Design19",
    "designName": "Lead Forensics",
    "designerName": "Rain",
    "tags": ["rainforest", "green", "retreat", "nature"],
    "categories": ["typography", "branding"],
    "likes": 24,
    "views": 340
  },
  {
    "id": 20,
    "src": "./src/assets/images/img20",
    "alt": "Design20",
    "designName": " Yum Yum Cookies",
    "designerName": "Zen",
    "tags": ["zen", "garden", "peaceful", "serene"],
    "categories": ["illustration", "web design"],
    "likes": 26,
    "views": 360
  },
  {
    "id": 21,
    "src": "./src/assets/images/img21",
    "alt": "Design21",
    "designName": "Basketball Team and sports",
    "designerName": "Urbanist",
    "tags": ["urban", "modern", "escape", "city"],
    "categories": ["architecture", "interior"],
    "likes": 30,
    "views": 450
},
{
    "id": 22,
    "src": "./src/assets/images/img22",
    "alt": "Design22",
    "designName": "Design or clone wordpress website",
    "designerName": "BluWave",
    "tags": ["ocean", "blue", "bliss", "water"],
    "categories": ["photography", "branding"],
    "likes": 50,
    "views": 600
},
{
    "id": 23,
    "src": "./src/assets/images/img23",
    "alt": "Design23",
    "designName": "My pt Hub website",
    "designerName": "PeakArtist",
    "tags": ["mountain", "majestic", "peak", "nature"],
    "categories": ["landscape", "illustration"],
    "likes": 40,
    "views": 500
},
{
    "id": 24,
    "src": "./src/assets/images/img24",
    "alt": "Design24",
    "designName": "clone and duplicate wordpress website",
    "designerName": "Sahara",
    "tags": ["desert", "mirage", "sand", "sunset"],
    "categories": ["photography", "digital art"],
    "likes": 35,
    "views": 420
},
{
    "id": 25,
    "src": "./src/assets/images/img25",
    "alt": "Design24",
    "designName": "Yoga website design",
    "designerName": "Sahara",
    "tags": ["desert", "mirage", "sand", "sunset"],
    "categories": ["photography", "digital art"],
    "likes": 35,
    "views": 520
}
];
